version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    working_directory: ~/backend_api
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ~/backend_api
          cache-path: node_modules
          override-ci-command: npm i
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: npx jest

      - run:
        name: deploy to app engine
        command : |
          gcloud config set project todo-app-backend-334910
          gcloud app deploy
  test:
    docker:
      - image: google/cloud-sdk:slim
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npx jest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
     